# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('country', models.CharField(max_length=40)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('email', models.CharField(max_length=60)),
                ('shit', models.IntegerField(default=0)),
            ],
        ),
    ]
