# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='shit',
        ),
    ]
